release:
  image: docker:19.03.1
  stage: build
  
  only:
    - master
    - tags

  services:
    - name: docker:19.03.1-dind
      command: ["--experimental"]

  before_script:
    - apk update && apk add bash && apk add git
    - git clone --recurse-submodules https://gitlab.merritt.es/music-library-player/release.git
    - cd release
    - git submodule update --remote backend
    - git submodule update --remote client

  script:
    - docker login -u hmerritt -p $DOCKER_PASS
    - docker build -t hmerritt/music-library-player:latest .
    - docker push hmerritt/music-library-player:latest
